# Inhalte der Leistungsseiten (Runde 3: ausführlich, SEO/GEO).
# Grundlage: Texte der bisherigen Hauptseite (06.10.2026) und die Lebensläufe der Zahnärztinnen.
# Allgemeine zahnmedizinische Erklärungen ohne Heilversprechen (Heilmittelwerbegesetz):
# keine Garantien, kein „schmerzfrei“, keine Vergleiche mit anderen Praxen. Keine Gedankenstriche.
#
# Felder: slug, icon, kurz (Menü), titel (H1), seo (Teil vor „| Zahnzentrum Messerschmidt“, max. ~32 Zeichen),
#   beschreibung (Meta, 140–160 Zeichen), teaser, kurz_erklaert (Antwortbox oben, für Google und KI-Suchen),
#   abschnitte [(H2, Text)], ablauf [(Schritt, Text)], fuer_wen [..], faq [(Frage, Antwort)],
#   aerztinnen [Schlüssel aus ZAHNAERZTINNEN in bauen.py], verwandt [slugs]

LEISTUNGEN = [
  dict(slug="saubere-zaehne", icon="zahnbuerste", kurz="Prophylaxe & PZR",
       titel="Prophylaxe und professionelle Zahnreinigung",
       seo="Prophylaxe & PZR in Mainz",
       beschreibung="Prophylaxe und professionelle Zahnreinigung (PZR) im Zahnzentrum Messerschmidt in Mainz-Laubenheim: Ablauf, Häufigkeit, Kosten und Tipps für die Pflege zu Hause.",
       teaser="Vorsorge, damit Ihre Zähne ein Leben lang gesund bleiben.",
       kurz_erklaert="Prophylaxe ist die Vorsorge gegen Karies und Zahnfleischerkrankungen. Kernstück ist die professionelle Zahnreinigung (PZR), bei der Beläge und Zahnstein auch an schwer erreichbaren Stellen entfernt werden. Wir empfehlen Erwachsenen mindestens einen, Kindern und Jugendlichen zwischen sechs und 18 Jahren zwei Termine im Jahr.",
       intro="Vorsorge ist in der Zahnmedizin die beste Behandlung. Mit regelmäßiger Prophylaxe erkennen wir Veränderungen früh und können vielen Problemen vorbeugen, bevor sie entstehen. Im Zahnzentrum Messerschmidt in Mainz-Laubenheim nehmen wir uns dafür Zeit.",
       abschnitte=[
        ("Warum Prophylaxe so wichtig ist", "Selbst bei gründlichem Putzen bleiben Beläge an Stellen zurück, die Zahnbürste und Zahnseide kaum erreichen: in den Zahnzwischenräumen, am Zahnfleischrand und auf den Kauflächen der hinteren Zähne. Aus diesen Belägen kann Zahnstein werden, in dem sich Bakterien gut halten. Sie gelten als Hauptursache für Karies und Entzündungen des Zahnfleisches. Regelmäßige Prophylaxe entfernt diese Beläge und hilft, Ihre Zähne und Ihr Zahnfleisch langfristig gesund zu halten."),
        ("Professionelle Zahnreinigung (PZR)", "Bei der PZR entfernen wir weiche und harte Beläge sowie Zahnstein, auch knapp unter dem Zahnfleischrand. Die Zahnzwischenräume reinigen wir gründlich, anschließend werden die Zähne poliert. Glatte Oberflächen bieten neuen Belägen weniger Halt. Zum Abschluss tragen wir auf Wunsch einen Fluoridlack auf, der den Zahnschmelz stärkt."),
        ("Pflege zu Hause: Putztechnik und Hilfsmittel", "Im Prophylaxetermin zeigen wir Ihnen, worauf es bei der täglichen Pflege ankommt. Wir besprechen die passende Putztechnik, den Einsatz von Zahnseide und Zwischenraumbürsten, die Wahl zwischen Hand- und elektrischer Zahnbürste und die richtige Zahnpasta. Denn auch die beste Prophylaxe ersetzt nicht die tägliche Pflege zu Hause, sie ergänzt sie."),
        ("Ernährung und Zahngesundheit", "Was und wie oft wir essen, beeinflusst die Zahngesundheit stark. Gerne beraten wir Sie zu zahnfreundlicher Ernährung, etwa zu häufigen Zwischenmahlzeiten, zuckerhaltigen Getränken oder säurehaltigen Lebensmitteln."),
        ("Prophylaxe für Kinder und Jugendliche", "Auch Kinder profitieren von regelmäßigen Besuchen. Sie lernen unsere Praxis entspannt kennen, und wir können die Entwicklung der Zähne begleiten. Für Kinder und Jugendliche zwischen sechs und 18 Jahren übernehmen die gesetzlichen Krankenkassen in der Regel die Kosten der Individualprophylaxe."),
        ("Was kostet eine PZR?", "Die professionelle Zahnreinigung ist für Erwachsene eine Privatleistung. Viele gesetzliche Krankenkassen bezuschussen sie, und bei Zahnzusatzversicherungen ist sie häufig enthalten. Die Kosten richten sich nach dem Aufwand. Sprechen Sie uns gerne an, wir informieren Sie vorher."),
       ],
       ablauf=[("Befund", "Wir sehen uns Zähne und Zahnfleisch an und zeigen Ihnen, wo sich Beläge bilden."),
               ("Reinigung", "Beläge und Zahnstein werden mit Ultraschall und Handinstrumenten entfernt, die Zwischenräume gründlich gereinigt."),
               ("Politur und Schutz", "Die Zähne werden poliert, auf Wunsch tragen wir Fluorid auf."),
               ("Beratung", "Wir geben Ihnen Tipps für die Pflege zu Hause und planen den nächsten Termin.")],
       fuer_wen=["alle, die ihre Zähne langfristig gesund halten möchten", "Patienten mit Implantaten, Kronen oder Brücken", "Menschen mit Neigung zu Zahnfleischbluten", "Kinder und Jugendliche ab dem Milchgebiss"],
       faq=[("Wie oft sollte ich zur professionellen Zahnreinigung?", "Für die meisten Erwachsenen ist ein bis zwei Mal im Jahr sinnvoll. Wie oft es bei Ihnen ratsam ist, hängt von Ihrem persönlichen Risiko ab und wir besprechen es im Termin."),
            ("Tut eine professionelle Zahnreinigung weh?", "Die meisten Patienten empfinden die PZR als gut auszuhalten. An empfindlichen Stellen arbeiten wir besonders behutsam. Sagen Sie uns gerne, wenn Ihnen etwas unangenehm ist."),
            ("Zahlt die Krankenkasse die PZR?", "Für Erwachsene ist die PZR eine Privatleistung. Viele gesetzliche Krankenkassen geben einen Zuschuss, Zahnzusatzversicherungen übernehmen sie oft ganz oder teilweise."),
            ("Wie lange dauert ein Prophylaxetermin?", "Das hängt vom Befund ab. Planen Sie in der Regel etwa eine Stunde ein.")],
       aerztinnen=["blatt", "messerschmidt"], verwandt=["feste-zaehne", "junge-zaehne", "schoenes-laecheln"]),

  dict(slug="schoenes-laecheln", icon="stern", kurz="Ästhetik",
       titel="Ästhetische Zahnheilkunde",
       seo="Ästhetische Zahnheilkunde Mainz",
       beschreibung="Ästhetische Zahnheilkunde in Mainz-Laubenheim: Bleaching, Veneers, zahnfarbene Füllungen und Wiederaufbau von Frontzähnen im Zahnzentrum Messerschmidt.",
       teaser="Bleaching, Veneers und natürliche Restaurationen für ein schönes Lächeln.",
       kurz_erklaert="Ästhetische Zahnheilkunde verbessert das Aussehen der Zähne, zum Beispiel durch Aufhellen (Bleaching), dünne Keramikschalen (Veneers) oder zahnfarbene Füllungen. Welche Behandlung passt, hängt von der Ursache ab: Verfärbung, abgebrochene Kanten, kleine Lücken oder ältere Füllungen. Wir beraten Sie dazu ausführlich und ehrlich.",
       intro="Kaffee, Tee, Rauchen oder Medikamente können Zähne mit der Zeit verfärben. Unfälle oder Erkrankungen führen manchmal zu abgebrochenen Zähnen oder Fehlstellungen. Im Zahnzentrum Messerschmidt bieten wir Ihnen verschiedene Möglichkeiten, Ihr Lächeln wieder strahlen zu lassen, mit Blick auf Gesundheit und Aussehen gleichermaßen.",
       abschnitte=[
        ("Professionelle Zahnreinigung als erster Schritt", "Oft ist eine gründliche professionelle Zahnreinigung schon der wichtigste Schritt zu helleren Zähnen. Beläge und oberflächliche Verfärbungen durch Kaffee, Tee oder Rauchen werden entfernt, die Zähne poliert. Danach sehen wir, ob eine weitere Behandlung überhaupt nötig ist."),
        ("Bleaching: Zähne schonend aufhellen", "Hartnäckige Verfärbungen lassen sich durch ein Bleaching reduzieren. Dabei wird ein Aufhellungsgel auf die Zähne aufgetragen. Vorher prüfen wir, ob Ihre Zähne und Ihr Zahnfleisch gesund sind und ob Füllungen oder Kronen im sichtbaren Bereich liegen, denn diese hellen nicht mit auf. Wie hell Ihre Zähne werden sollen, besprechen wir individuell mit Ihnen."),
        ("Veneers: dünne Keramikschalen", "Veneers sind hauchdünne Schalen aus Keramik, die auf die Vorderseite der Zähne geklebt werden. Sie eignen sich für kleine Defekte, leichte Fehlstellungen, Lücken oder einzelne stark verfärbte Zähne. Dafür muss in der Regel nur wenig Zahnsubstanz abgetragen werden."),
        ("Zahnfarbene Füllungen und Wiederaufbau", "Abgebrochene Frontzahnkanten bauen wir mit zahnfarbenem Komposit wieder auf, kleine Lücken lassen sich auf die gleiche Weise schließen. Auch ältere, dunkle Füllungen können durch zahnfarbene Materialien ersetzt werden."),
        ("Kronen und Implantate im sichtbaren Bereich", "Fehlt ein Zahn oder ist er stark geschädigt, kommen Kronen aus Keramik oder ein Implantat in Frage. Unser eigenes Dentallabor stimmt Form und Farbe auf Ihre natürlichen Zähne ab."),
       ],
       ablauf=[("Beratung", "Sie erzählen uns, was Sie stört. Wir untersuchen Zähne und Zahnfleisch und erklären die Möglichkeiten."),
               ("Planung", "Gemeinsam wählen wir die passende Behandlung und besprechen Ergebnis, Aufwand und Kosten."),
               ("Behandlung", "Je nach Verfahren in einem oder mehreren Terminen."),
               ("Nachsorge", "Regelmäßige Kontrollen und Prophylaxe helfen, das Ergebnis lange zu erhalten.")],
       fuer_wen=["Menschen mit verfärbten oder dunklen Zähnen", "Patienten mit abgebrochenen Kanten oder kleinen Lücken", "alle, die ältere Füllungen durch zahnfarbene ersetzen möchten"],
       faq=[("Schadet Bleaching den Zähnen?", "Bei gesunden Zähnen und fachgerechter Anwendung gilt Bleaching als gut verträglich. Vorübergehend können die Zähne empfindlicher sein. Wir prüfen vorher, ob Bleaching für Sie geeignet ist."),
            ("Wie lange hält ein Bleaching?", "Das ist individuell und hängt stark von Ihren Gewohnheiten ab, zum Beispiel Kaffee, Tee oder Rauchen. Gute Pflege und regelmäßige PZR helfen, das Ergebnis zu erhalten."),
            ("Übernimmt die Krankenkasse ästhetische Behandlungen?", "Rein ästhetische Behandlungen wie Bleaching oder Veneers sind in der Regel Privatleistungen. Wir informieren Sie vorher über die Kosten."),
            ("Werden Füllungen und Kronen beim Bleaching heller?", "Nein, Füllungen, Kronen und Veneers verändern ihre Farbe nicht. Das berücksichtigen wir bei der Planung.")],
       aerztinnen=["messerschmidt", "blatt"], verwandt=["saubere-zaehne", "neue-zaehne"]),

  dict(slug="feste-zaehne", icon="zahnfleisch", kurz="Parodontologie",
       titel="Parodontologie: Behandlung von Parodontitis",
       seo="Parodontitis-Behandlung Mainz",
       beschreibung="Parodontitis erkennen und behandeln in Mainz-Laubenheim: Anzeichen, Ablauf und Nachsorge im Zahnzentrum Messerschmidt mit Schwerpunkt Parodontologie.",
       teaser="Früh erkennen und gezielt behandeln, damit Ihre Zähne fest bleiben.",
       kurz_erklaert="Parodontitis ist eine bakterielle Entzündung des Zahnhalteapparats. Typische Anzeichen sind Zahnfleischbluten, Rötungen, Mundgeruch und zurückgehendes Zahnfleisch. Unbehandelt kann sich der Kieferknochen abbauen und Zähne können sich lockern. Dr. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Parodontologie.",
       intro="Parodontitis ist eine der häufigsten Erkrankungen in der Zahnmedizin und kann in jedem Alter auftreten. Bei manchen Patienten ist nur ein Zahn betroffen, bei anderen mehrere in unterschiedlichem Ausmaß. Unser Ziel ist es, Parodontitis früh zu erkennen und rechtzeitig zu behandeln.",
       abschnitte=[
        ("Wie entsteht Parodontitis?", "Bakterien sammeln sich zwischen Zahn und Zahnfleisch, in den sogenannten Zahnfleischtaschen. Werden sie nicht entfernt, bilden sich Beläge und Zahnstein. Das Zahnfleisch entzündet sich, und die Entzündung kann auf den Kieferknochen übergreifen. Rauchen, Diabetes, Stress und eine erbliche Veranlagung können das Risiko erhöhen."),
        ("Anzeichen ernst nehmen", "Zahnfleischbluten beim Putzen, gerötetes oder geschwollenes Zahnfleisch, Mundgeruch, empfindliche Zahnhälse oder Zähne, die länger wirken, können auf eine Parodontitis hinweisen. Weil die Erkrankung oft lange keine Schmerzen macht, wird sie häufig spät bemerkt. Gerade deshalb sind regelmäßige Kontrollen wichtig."),
        ("Gründliche Befundaufnahme", "Wir messen die Tiefe der Zahnfleischtaschen, prüfen die Beweglichkeit der Zähne, erfassen Blutungspunkte und freiliegende Zahnhälse. Bei Bedarf ergänzen Röntgenaufnahmen das Bild. Daraus erstellen wir Ihren persönlichen Therapieplan."),
        ("Die Behandlung", "Im Mittelpunkt steht die gründliche Reinigung der Zahnfleischtaschen mit Ultraschall und feinen Handinstrumenten, unter örtlicher Betäubung. Je nach Befund setzen wir auch unser Lasersystem ein. In fortgeschrittenen Fällen kann ein Wiederaufbau von zerstörtem Gewebe und Knochen sinnvoll sein. Dr. Sabine Messerschmidt ist auf regenerative Parodontaltherapie und Parodontalchirurgie spezialisiert."),
        ("Nachsorge: das Ergebnis erhalten", "Nach der Behandlung ist eine regelmäßige unterstützende Parodontitistherapie wichtig. In festen Abständen kontrollieren wir die Zahnfleischtaschen und reinigen sie professionell. So helfen wir, dass Ihr Zahnfleisch gesund bleibt und Ihre Zähne fest sitzen."),
       ],
       ablauf=[("Untersuchung", "Messung der Zahnfleischtaschen und Befundaufnahme."),
               ("Vorbehandlung", "Professionelle Reinigung und Anleitung zur häuslichen Pflege."),
               ("Therapie", "Reinigung der Zahnfleischtaschen unter örtlicher Betäubung, bei Bedarf mit Laser."),
               ("Kontrolle und Nachsorge", "Erneute Messung und regelmäßige unterstützende Therapie.")],
       fuer_wen=["Patienten mit Zahnfleischbluten oder Mundgeruch", "Menschen mit zurückgehendem Zahnfleisch oder lockeren Zähnen", "Raucher und Menschen mit Diabetes", "Patienten vor einer Implantatversorgung"],
       faq=[("Ist Parodontitis heilbar?", "Eine Parodontitis lässt sich gut behandeln und zum Stillstand bringen. Damit sie nicht wiederkommt, sind gute Pflege zu Hause und regelmäßige Nachsorge entscheidend."),
            ("Ist die Behandlung schmerzhaft?", "Die Reinigung der Zahnfleischtaschen erfolgt unter örtlicher Betäubung. Danach kann das Zahnfleisch einige Tage empfindlich sein."),
            ("Zahlt die gesetzliche Krankenkasse die Parodontitis-Behandlung?", "Die systematische Parodontitistherapie ist bei entsprechendem Befund eine Leistung der gesetzlichen Krankenkassen. Einzelne Zusatzleistungen können privat sein. Wir beraten Sie vorher."),
            ("Hat Parodontitis Folgen für den ganzen Körper?", "Studien zeigen Zusammenhänge zwischen Parodontitis und Allgemeinerkrankungen wie Diabetes. Sprechen Sie uns an, wenn Sie Vorerkrankungen haben.")],
       aerztinnen=["messerschmidt"], verwandt=["saubere-zaehne", "neue-zaehne", "gekonnte-eingriffe"]),

  dict(slug="neue-zaehne", icon="implantat", kurz="Zahnersatz & Implantate",
       titel="Zahnersatz und Implantologie",
       seo="Implantate & Zahnersatz Mainz",
       beschreibung="Implantate, Kronen, Brücken und Inlays aus dem eigenen Dentallabor in Mainz-Laubenheim. Implantologie mit Schwerpunkt DGI und APW im Zahnzentrum Messerschmidt.",
       teaser="Füllungen, Kronen, Brücken und Implantate aus dem eigenen Labor.",
       kurz_erklaert="Fehlt ein Zahn oder ist er stark geschädigt, gibt es mehrere Wege: Füllung, Inlay, Krone, Brücke, Prothese oder Implantat. Ein Implantat ist eine künstliche Zahnwurzel, die im Kiefer einheilt und eine Krone trägt. Kronen, Brücken und Inlays fertigen wir im eigenen Dentallabor. Dr. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Implantologie (DGI und APW).",
       intro="Trotz guter Pflege braucht ein Zahn manchmal eine Füllung oder muss ersetzt werden. Ob Füllung, Inlay, Krone, Brücke, Prothese oder Implantat: Wir finden mit Ihnen die Lösung, die zu Ihrer Situation passt, und fertigen viele Arbeiten direkt im eigenen Haus.",
       abschnitte=[
        ("Füllungen", "Nach dem Entfernen der Karies verschließen wir den Zahn mit einer passenden Füllung. Zur Wahl stehen zahnfarbener Kunststoff (Komposit), Keramik oder Gold. Welches Material sinnvoll ist, hängt von Größe und Lage des Defekts ab."),
        ("Inlays aus Keramik oder Gold", "Bei größeren Defekten sind Inlays eine stabile Lösung. Sie werden nach einem Abdruck passgenau im Labor gefertigt und dann wie ein Puzzleteil in den Zahn eingesetzt."),
        ("Kronen und Brücken aus dem eigenen Labor", "Ist ein Zahn stark geschädigt, schützt eine Krone die verbliebene Substanz. Eine Brücke schließt eine Lücke, indem sie an den Nachbarzähnen befestigt wird. Kronen, Brücken und Inlays aus Keramik oder Gold fertigen wir in unserem hauseigenen Dentallabor. Das ermöglicht kurze Wege und schnelle Anpassungen. Für besondere Arbeiten und größere Prothesen arbeiten wir mit deutschen Meisterlaboren zusammen."),
        ("Implantate: die künstliche Zahnwurzel", "Ein Implantat ersetzt die Zahnwurzel. Es wird in den Kieferknochen eingesetzt und heilt dort ein. Danach trägt es eine Krone, eine Brücke oder dient als Halt für eine Prothese. Ein Vorteil: Die Nachbarzähne müssen dafür nicht beschliffen werden. Dr. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Implantologie der DGI und APW und ist auf Augmentationschirurgie spezialisiert, also den Aufbau von Kieferknochen, wenn dieser für ein Implantat nicht ausreicht."),
        ("Herausnehmbarer Zahnersatz", "Fehlen mehrere oder alle Zähne, kann eine Teil- oder Vollprothese die Lösung sein. Mit Implantaten lässt sich eine Prothese zusätzlich sicher befestigen."),
       ],
       ablauf=[("Beratung und Planung", "Untersuchung, bei Bedarf Röntgen, und Besprechung der Möglichkeiten und Kosten."),
               ("Vorbereitung", "Zum Beispiel Behandlung von Karies oder Parodontitis, bei Implantaten eventuell Knochenaufbau."),
               ("Behandlung", "Präparation, Abdruck oder Implantation, je nach Versorgung."),
               ("Fertigung und Eingliederung", "Unser Labor fertigt den Zahnersatz, wir setzen ihn ein und prüfen den Biss.")],
       fuer_wen=["Patienten mit Karies oder alten, undichten Füllungen", "Menschen mit fehlenden Zähnen", "Prothesenträger, die mehr Halt wünschen"],
       faq=[("Wie lange dauert eine Implantatbehandlung?", "Das ist unterschiedlich. Meist braucht das Implantat einige Wochen bis Monate zum Einheilen, bevor die Krone eingesetzt wird. Ist ein Knochenaufbau nötig, dauert es länger."),
            ("Bin ich für ein Implantat geeignet?", "Entscheidend sind unter anderem ausreichend Kieferknochen, gesundes Zahnfleisch und Ihre allgemeine Gesundheit. Das klären wir in einer ausführlichen Untersuchung."),
            ("Was zahlt die Krankenkasse bei Zahnersatz?", "Die gesetzlichen Krankenkassen zahlen einen Festzuschuss, der sich am Befund orientiert. Vor jeder Behandlung erhalten Sie einen Heil- und Kostenplan."),
            ("Welcher Vorteil hat das eigene Dentallabor?", "Kurze Wege: Farbe, Form und Passung können wir direkt abstimmen und bei Bedarf schnell anpassen.")],
       aerztinnen=["messerschmidt", "miller"], verwandt=["feste-zaehne", "schoenes-laecheln", "gekonnte-eingriffe"]),

  dict(slug="erhaltende-zaehne", icon="wurzel", kurz="Endodontie",
       titel="Endodontie: Wurzelbehandlung",
       seo="Wurzelbehandlung in Mainz",
       beschreibung="Wurzelbehandlung in Mainz-Laubenheim: wann sie nötig ist, wie sie abläuft und wie Ihr eigener Zahn erhalten bleiben kann. Zahnzentrum Messerschmidt.",
       teaser="Wurzelbehandlung und Wurzelspitzenresektion, damit Ihr eigener Zahn bleibt.",
       kurz_erklaert="Bei einer Wurzelbehandlung wird entzündetes oder abgestorbenes Gewebe aus dem Inneren des Zahns entfernt, der Wurzelkanal gereinigt, desinfiziert und dicht verfüllt. So kann ein Zahn oft erhalten werden, der sonst gezogen werden müsste. Olga Miller und Dr. Alina Günther haben Arbeitsschwerpunkte in komplexen endodontischen Behandlungen.",
       intro="Unser Ziel ist es, Ihre eigenen Zähne so lange wie möglich zu erhalten, auch wenn ein Zahn erkrankt ist. Die Endodontie, also die Behandlung im Inneren des Zahns, hilft in vielen Fällen, das Ziehen eines Zahnes zu vermeiden.",
       abschnitte=[
        ("Wann ist eine Wurzelbehandlung nötig?", "Im Inneren jedes Zahns liegt die Pulpa mit Nerven und Blutgefäßen. Dringen Bakterien zum Beispiel durch tiefe Karies ein, oder wird der Zahn durch einen Unfall verletzt, kann sich dieses Gewebe entzünden oder absterben. Typische Anzeichen sind starke, pochende Schmerzen, Empfindlichkeit auf Wärme oder Kälte und Schmerzen beim Aufbeißen. Manchmal verläuft die Entzündung aber auch ohne Beschwerden und fällt erst auf dem Röntgenbild auf."),
        ("So läuft die Wurzelkanalbehandlung ab", "Unter örtlicher Betäubung öffnen wir den Zahn über die Krone, entfernen das entzündete Gewebe vollständig und bereiten die Wurzelkanäle mit feinen Instrumenten auf. Die Kanäle werden gründlich gespült und desinfiziert. Je nach Befund legen wir eine Einlage ein und verschließen den Zahn vorübergehend. Zum Schluss werden die Kanäle dicht verfüllt."),
        ("Wurzelspitzenresektion", "Heilt eine Entzündung an der Wurzelspitze trotz Wurzelbehandlung nicht aus, kann eine Wurzelspitzenresektion helfen. Dabei wird die Wurzelspitze in einem kleinen chirurgischen Eingriff über den Kieferknochen entfernt. Auch diese Methode dient dazu, den Zahn zu erhalten."),
        ("Und danach?", "Ein wurzelbehandelter Zahn kann viele Jahre seine Aufgabe erfüllen. Weil er nach der Behandlung spröder werden kann, braucht er oft einen stabilen Aufbau: eine Füllung, ein Inlay oder eine Krone. Was sinnvoll ist, entscheiden wir anhand des Befundes. Alle Kronen und Inlays fertigt unser Labor."),
       ],
       ablauf=[("Diagnose", "Untersuchung und Röntgenbild zeigen, wie stark der Zahn betroffen ist."),
               ("Reinigung der Kanäle", "Unter örtlicher Betäubung wird das Gewebe entfernt und der Kanal desinfiziert."),
               ("Verfüllung", "Die Wurzelkanäle werden dicht verschlossen."),
               ("Aufbau", "Füllung, Inlay oder Krone schützen den Zahn langfristig.")],
       fuer_wen=["Patienten mit starken Zahnschmerzen oder Entzündungen", "Zähne nach einem Unfall", "Zähne mit Entzündung an der Wurzelspitze"],
       faq=[("Tut eine Wurzelbehandlung weh?", "Die Behandlung erfolgt unter örtlicher Betäubung. Viele Patienten spüren danach eine deutliche Erleichterung, weil der Entzündungsschmerz nachlässt. Einige Tage kann der Zahn noch empfindlich sein."),
            ("Wie viele Termine braucht eine Wurzelbehandlung?", "Häufig sind es ein bis drei Termine, je nach Anzahl und Form der Wurzelkanäle und Ausmaß der Entzündung."),
            ("Ist ein Implantat nicht einfacher?", "Wo es möglich ist, lohnt es sich, den eigenen Zahn zu erhalten. Ob das in Ihrem Fall sinnvoll ist, besprechen wir ehrlich mit Ihnen."),
            ("Was übernimmt die Krankenkasse?", "Wurzelbehandlungen sind unter bestimmten Voraussetzungen Kassenleistung. Für einzelne Zusatzleistungen können Kosten entstehen, über die wir Sie vorher informieren.")],
       aerztinnen=["miller", "guenther", "messerschmidt"], verwandt=["neue-zaehne", "gekonnte-eingriffe"]),

  dict(slug="junge-zaehne", icon="kind", kurz="Kinderzahnheilkunde",
       titel="Kinder- und Jugendzahnheilkunde",
       seo="Kinderzahnarzt in Mainz",
       beschreibung="Kinderzahnheilkunde in Mainz-Laubenheim: der erste Zahnarztbesuch, Prophylaxe für Kinderzähne und Begleitung beim Zahnwechsel im Zahnzentrum Messerschmidt.",
       teaser="Mit Geduld und Humor: der entspannte Zahnarztbesuch für Kinder.",
       kurz_erklaert="Kinder sollten zum ersten Mal in die Zahnarztpraxis kommen, sobald die ersten Zähne da sind. Bis sechs Jahre empfehlen wir einen, ab sechs Jahren zwei Kontrolltermine im Jahr. Wir führen Kinder behutsam an die Behandlung heran, damit der Zahnarztbesuch eine gute Erfahrung wird.",
       intro="Mit dem ersten Zahn kommen viele Fragen: Wie oft putzen? Ab wann putzt mein Kind selbst? Braucht es schon Zahnseide? Und wann zum ersten Mal zum Zahnarzt? Unsere Antwort auf die letzte Frage: Kommen Sie gerne, sobald die ersten Zähne da sind.",
       abschnitte=[
        ("Der erste Besuch", "Für Kinder ist der erste Besuch aufregend, und auch Eltern sind manchmal unsicher. Am schönsten ist es, wenn Ihr Kind ohne Beschwerden zum Schnuppern kommt. So lernen wir uns ganz ohne Druck kennen. Ihr Kind darf sich alles ansehen, auf dem Behandlungsstuhl fahren und Fragen stellen. Damit legen wir den Grundstein für entspannte Kontrolltermine."),
        ("Zahnpflege bei Kindern", "Wir beraten Sie zur Pflege der Milchzähne: welche Zahnbürste und Zahnpasta geeignet ist, wie viel Fluorid sinnvoll ist und wie lange Eltern nachputzen sollten. Milchzähne sind wichtig, auch wenn sie später ausfallen. Sie halten den Platz für die bleibenden Zähne frei und sind wichtig für Kauen und Sprechen."),
        ("Prophylaxe für Kinderzähne", "Regelmäßige Kontrollen und Prophylaxe helfen, Karies früh zu erkennen und vorzubeugen. Dazu gehören zum Beispiel das Fluoridieren und bei Bedarf das Versiegeln der Kauflächen der bleibenden Backenzähne. Für Kinder und Jugendliche übernehmen die gesetzlichen Krankenkassen viele dieser Leistungen."),
        ("Begleitung beim Zahnwechsel", "Wir beobachten die Entwicklung des Gebisses beim Zahnwechsel. Zeigt sich, dass Zähne oder Kiefer sich ungünstig entwickeln, raten wir rechtzeitig zu einer kieferorthopädischen Untersuchung."),
        ("Patenschaft für Kindergärten", "Als Patenschaftszahnarzt im Arbeitskreis Jugendzahnpflege betreuen wir zwei Kindergärten in Mainz-Laubenheim. Die Kinder erkunden einmal im Jahr unsere Praxis, und wir besuchen sie mit Handpuppen und Mitmachspielen im Kindergarten. So wird der Zahnarzt zum Freund."),
       ],
       ablauf=[("Kennenlernen", "Ihr Kind schaut sich in Ruhe um und darf alles ausprobieren."),
               ("Kontrolle", "Wir sehen uns die Zähne spielerisch an und erklären, was wir tun."),
               ("Beratung", "Sie erhalten Tipps zur Pflege und Ernährung."),
               ("Nächster Termin", "Regelmäßige Besuche machen die Praxis vertraut.")],
       fuer_wen=["Kleinkinder ab dem ersten Zahn", "Kinder im Zahnwechsel", "Jugendliche bis 18 Jahre"],
       faq=[("Wann sollte mein Kind zum ersten Mal zum Zahnarzt?", "Am besten, sobald die ersten Milchzähne da sind. Dann lernt Ihr Kind die Praxis ohne Beschwerden kennen."),
            ("Wie oft sollten Kinder zur Kontrolle?", "Bis sechs Jahre empfehlen wir einmal, ab sechs Jahren zweimal im Jahr."),
            ("Was kann ich tun, wenn mein Kind Angst hat?", "Sprechen Sie positiv über den Besuch und vermeiden Sie Sätze wie „es tut nicht weh“. Wir nehmen uns Zeit und gehen in kleinen Schritten vor."),
            ("Übernimmt die Krankenkasse die Prophylaxe für Kinder?", "Für Kinder und Jugendliche zwischen sechs und 18 Jahren übernehmen die gesetzlichen Krankenkassen die Individualprophylaxe. Auch für jüngere Kinder gibt es Früherkennungsuntersuchungen als Kassenleistung.")],
       aerztinnen=[], verwandt=["saubere-zaehne", "stressfreier-besuch"]),

  dict(slug="gesundes-kiefergelenk", icon="kiefer", kurz="Funktionsdiagnostik",
       titel="Funktionsdiagnostik und CMD",
       seo="CMD & Funktionsdiagnostik Mainz",
       beschreibung="Funktionsdiagnostik bei CMD in Mainz-Laubenheim: Ursachen von Kieferschmerzen, Knirschen und Verspannungen finden und gezielt behandeln im Zahnzentrum Messerschmidt.",
       teaser="Wenn Kiefer, Kopf oder Nacken schmerzen: Ursachen gezielt finden.",
       kurz_erklaert="CMD (Craniomandibuläre Dysfunktion) ist eine Störung im Zusammenspiel von Kiefergelenken, Kaumuskulatur und Zähnen. Sie kann Kieferschmerzen, Knacken im Kiefergelenk, Kopfschmerzen oder Nackenverspannungen auslösen. Mit einer Funktionsdiagnostik untersuchen wir dieses Zusammenspiel und erstellen einen passenden Therapieplan.",
       intro="Schmerzen im Kiefergelenk, Verspannungen im Nacken, Kopfschmerzen oder nächtliches Zähneknirschen können auf eine Craniomandibuläre Dysfunktion hinweisen. Die Beschwerden sind vielfältig und werden deshalb oft nicht sofort mit den Zähnen in Verbindung gebracht.",
       abschnitte=[
        ("Mögliche Anzeichen einer CMD", "Häufige Hinweise sind Schmerzen oder Knacken im Kiefergelenk, eine eingeschränkte Mundöffnung, Kopf-, Gesichts- oder Nackenschmerzen, Verspannungen und abgenutzte Zähne durch Knirschen oder Pressen. Auch Ohrgeräusche können im Zusammenhang stehen. Nicht jede dieser Beschwerden hat ihre Ursache im Kiefer, deshalb ist eine sorgfältige Untersuchung wichtig."),
        ("Mögliche Ursachen", "Eine CMD kann verschiedene Gründe haben: Stress und nächtliches Knirschen, ungünstige Bisslagen, schlecht sitzender Zahnersatz oder Veränderungen nach einer kieferorthopädischen Behandlung oder Zahnentfernung."),
        ("So untersuchen wir", "Bei der Funktionsdiagnostik prüfen wir Kiefergelenke und Zähne, die Bewegungen des Unterkiefers und die Kaumuskulatur, und wie diese zusammenspielen. Wir tasten Muskeln und Gelenke ab, achten auf Geräusche und Bewegungseinschränkungen und analysieren den Biss."),
        ("Behandlung", "Häufig kommt eine individuell angefertigte Aufbissschiene zum Einsatz, die Kiefer und Muskulatur entlastet. Je nach Befund ergänzen wir die Behandlung, zum Beispiel durch Anpassungen am Biss. Bei Bedarf arbeiten wir mit Physiotherapeuten oder Ärzten anderer Fachrichtungen zusammen."),
        ("Vor größeren Behandlungen", "Eine Funktionsdiagnostik ist auch sinnvoll, bevor Sie umfangreichen Zahnersatz oder eine größere kieferorthopädische oder konservierende Behandlung erhalten. So kann der neue Biss auf Ihre Kiefergelenke abgestimmt werden."),
       ],
       ablauf=[("Gespräch", "Sie schildern Ihre Beschwerden, wir fragen nach Vorgeschichte und Gewohnheiten."),
               ("Untersuchung", "Kiefergelenke, Muskulatur, Unterkieferbewegung und Biss."),
               ("Therapieplan", "Zum Beispiel Aufbissschiene und begleitende Maßnahmen."),
               ("Kontrolle", "Wir prüfen, wie die Behandlung wirkt, und passen sie an.")],
       fuer_wen=["Menschen mit Kieferschmerzen oder Knacken im Kiefergelenk", "Patienten, die nachts knirschen oder pressen", "Patienten vor umfangreichem Zahnersatz"],
       faq=[("Was ist eine Aufbissschiene?", "Eine Schiene aus Kunststoff, die meist nachts getragen wird. Sie schützt die Zähne vor dem Abrieb durch Knirschen und kann Kiefer und Muskulatur entlasten."),
            ("Woran erkenne ich, dass ich nachts knirsche?", "Hinweise sind morgendliche Verspannungen im Kiefer, Kopfschmerzen oder abgenutzte Zahnkanten. Manchmal bemerkt es auch der Partner."),
            ("Zahlt die Krankenkasse die Funktionsdiagnostik?", "Die Funktionsdiagnostik ist meist eine Privatleistung. Eine Aufbissschiene kann bei entsprechender Diagnose eine Kassenleistung sein. Wir informieren Sie vorab.")],
       aerztinnen=["messerschmidt"], verwandt=["neue-zaehne", "stressfreier-besuch"]),

  dict(slug="stressfreier-besuch", icon="herz", kurz="Angstpatienten",
       titel="Angst vor dem Zahnarzt? Entspannt zur Behandlung",
       seo="Zahnarzt für Angstpatienten Mainz",
       beschreibung="Zahnarzt für Angstpatienten in Mainz-Laubenheim: Zeit, Ruhe, verständliche Erklärungen und auf Wunsch begleitende Akupunktur im Zahnzentrum Messerschmidt.",
       teaser="Wir nehmen Ihre Sorgen ernst und nehmen uns Zeit für Sie.",
       kurz_erklaert="Viele Menschen haben ein mulmiges Gefühl vor dem Zahnarztbesuch. Bei uns können Sie Ihre Angst offen ansprechen. Wir planen mehr Zeit ein, erklären jeden Schritt, vereinbaren auf Wunsch Pausenzeichen und bieten begleitend Akupunktur an. Dr. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Akupunktur.",
       intro="Sie fühlen sich unwohl beim Gedanken an den nächsten Zahnarzttermin? Dann sind Sie bei uns herzlich willkommen. Wir nehmen Ihre Sorgen ernst und tun alles dafür, dass Sie sich bei uns gut aufgehoben fühlen, vom ersten Anruf bis zum Ende der Behandlung.",
       abschnitte=[
        ("Sagen Sie es uns", "Sprechen Sie Ihre Angst gerne schon bei der Terminvereinbarung an. Dann planen wir mehr Zeit ein, damit nichts unter Zeitdruck passiert. Viele Patienten erleben schon als erleichternd, dass sie sich nicht erklären müssen."),
        ("Erst reden, dann behandeln", "Beim ersten Termin geht es oft nur ums Kennenlernen. Wir sprechen über Ihre Erfahrungen und Wünsche, schauen uns die Zähne in Ruhe an und erklären, was wir sehen. Behandelt wird erst, wenn Sie dazu bereit sind."),
        ("Sie behalten die Kontrolle", "Vor jedem Schritt erklären wir, was als Nächstes passiert. Wir vereinbaren ein Handzeichen, mit dem Sie jederzeit eine Pause machen können. Viele Patienten fühlen sich dadurch deutlich sicherer."),
        ("Ruhige Atmosphäre", "Unsere Praxis liegt in einem hellen, freundlich gestalteten Haus, weit weg vom kühlen Bild klassischer Zahnarztpraxen. Unser Team nimmt sich Zeit und sorgt für eine entspannte Stimmung."),
        ("Betäubung und begleitende Verfahren", "Selbstverständlich arbeiten wir mit örtlicher Betäubung, auch das Setzen der Spritze erfolgt behutsam. Auf Wunsch bieten wir begleitend Akupunktur zur Entspannung an. Bei bestimmten Eingriffen, etwa dem Entfernen von Weisheitszähnen, ist auch eine Behandlung in Vollnarkose möglich. Welche Möglichkeiten für Sie in Frage kommen, besprechen wir persönlich."),
       ],
       ablauf=[("Anruf", "Sagen Sie bei der Terminvereinbarung, dass Sie Angst haben."),
               ("Kennenlernen", "Gespräch und Untersuchung in Ruhe, ohne Behandlung."),
               ("Plan", "Wir besprechen Schritt für Schritt, was nötig ist, und wie wir vorgehen."),
               ("Behandlung", "In Ihrem Tempo, mit Pausen und verständlichen Erklärungen.")],
       fuer_wen=["Menschen mit Zahnarztangst oder schlechten Erfahrungen", "Patienten, die lange nicht beim Zahnarzt waren", "alle, die sich mehr Zeit und Ruhe wünschen"],
       faq=[("Ich war jahrelang nicht beim Zahnarzt. Ist das schlimm?", "Nein. Wir machen Ihnen keine Vorwürfe. Wichtig ist, dass Sie jetzt kommen. Gemeinsam verschaffen wir uns einen Überblick und gehen Schritt für Schritt vor."),
            ("Kann ich eine Begleitperson mitbringen?", "Ja, gerne. Sprechen Sie uns bei der Terminvereinbarung darauf an."),
            ("Wird beim ersten Termin schon behandelt?", "Nur wenn Sie es möchten oder akute Schmerzen haben. Der erste Termin dient vor allem dem Kennenlernen."),
            ("Hilft Akupunktur gegen Zahnarztangst?", "Manche Patienten empfinden Akupunktur als entspannend. Ob sie für Sie in Frage kommt, besprechen wir gerne persönlich.")],
       aerztinnen=["messerschmidt"], verwandt=["junge-zaehne", "saubere-zaehne"]),

  dict(slug="gekonnte-eingriffe", icon="skalpell", kurz="Oralchirurgie",
       titel="Oralchirurgie",
       seo="Oralchirurgie in Mainz",
       beschreibung="Oralchirurgie in Mainz-Laubenheim: Weisheitszähne entfernen, Wurzelspitzenresektion, Knochenaufbau und kleine Eingriffe im Zahnzentrum Messerschmidt.",
       teaser="Von der Weisheitszahn-OP bis zum Kieferaufbau, ausführlich erklärt.",
       kurz_erklaert="Die Oralchirurgie umfasst Eingriffe an Zähnen, Mundhöhle und Kiefer, zum Beispiel das Entfernen von Weisheitszähnen, die Wurzelspitzenresektion, den Knochenaufbau für Implantate oder die Korrektur von Lippen- und Zungenbändchen. Eingriffe erfolgen in der Regel unter örtlicher Betäubung, auf Wunsch auch in Vollnarkose.",
       intro="Die Oralchirurgie ist ein Teilbereich der Zahnmedizin. Unser Spektrum reicht von kleinen Eingriffen wie der Korrektur von Lippen- und Zungenbändchen über die Entfernung von Weisheitszähnen bis zu Kiefer- und Zahnfleischoperationen. Vor jedem Eingriff nehmen wir uns Zeit für eine ausführliche Aufklärung.",
       abschnitte=[
        ("Weisheitszähne entfernen", "Weisheitszähne brechen meist zwischen 18 und 25 Jahren durch, bei manchen Menschen nie. Sie müssen nicht immer entfernt werden. Gründe dafür können wiederkehrende Entzündungen, Karies, Zysten oder Platzmangel sein, durch den sich andere Zähne verschieben. Der Eingriff erfolgt in der Regel unter örtlicher Betäubung, auf Wunsch auch in Vollnarkose."),
        ("Wurzelspitzenresektion", "Ist die Spitze einer Zahnwurzel dauerhaft entzündet, kann sie über einen kleinen Zugang durch den Kieferknochen entfernt werden. Ziel ist es, den Zahn zu erhalten."),
        ("Knochenaufbau (Augmentation)", "Reicht der Kieferknochen für ein Implantat nicht aus, kann er aufgebaut werden. Dr. Sabine Messerschmidt ist auf Augmentationschirurgie und komplexe prothetisch-chirurgische Rekonstruktionen spezialisiert."),
        ("Kleine Eingriffe", "Dazu gehören zum Beispiel die Korrektur eines zu kurzen Lippen- oder Zungenbändchens oder das Freilegen von Zähnen."),
        ("Ausführliche Aufklärung und Nachsorge", "Vor jedem Eingriff erklären wir Ihnen alle Schritte und beantworten Ihre Fragen. Nach der Operation erhalten Sie klare Hinweise, worauf Sie achten sollten. Die wichtigsten Tipps finden Sie auch auf unserer Seite Patienteninfos."),
       ],
       ablauf=[("Untersuchung", "Befund, bei Bedarf Röntgen, und Planung des Eingriffs."),
               ("Aufklärung", "Wir erklären Ablauf, Betäubung und mögliche Risiken."),
               ("Eingriff", "In der Regel unter örtlicher Betäubung, auf Wunsch in Vollnarkose."),
               ("Nachsorge", "Kontrolle der Wundheilung und klare Verhaltenstipps.")],
       fuer_wen=["Patienten mit Beschwerden durch Weisheitszähne", "Zähne mit Entzündung an der Wurzelspitze", "Patienten vor einer Implantatversorgung mit wenig Knochen"],
       faq=[("Müssen Weisheitszähne immer raus?", "Nein. Wir entfernen Weisheitszähne nur, wenn es einen Grund gibt, zum Beispiel Entzündungen oder Platzmangel."),
            ("Wie lange bin ich nach einer Weisheitszahn-OP eingeschränkt?", "Schwellungen und Beschwerden klingen meist innerhalb einiger Tage ab. Planen Sie nach dem Eingriff Ruhe ein."),
            ("Darf ich nach dem Eingriff Auto fahren?", "Nach einer örtlichen Betäubung empfehlen wir, nicht selbst zu fahren, wenn Sie sich beeinträchtigt fühlen. Nach einer Vollnarkose dürfen Sie 12 bis 24 Stunden nicht selbst fahren."),
            ("Was sollte ich nach der OP beachten?", "Kein Sport, keine heißen Speisen und Getränke, kein Alkohol und Rauchen, keine ASS-haltigen Schmerzmittel. Die vollständigen Hinweise finden Sie auf unserer Seite Patienteninfos.")],
       aerztinnen=["messerschmidt", "guenther"], verwandt=["neue-zaehne", "erhaltende-zaehne"]),
]
