# Inhalte der Leistungsseiten. Grundlage: Texte der bisherigen Hauptseite (ausgelesen 06.10.2026),
# gekürzt und neu formuliert. Keine Heilversprechen (Heilmittelwerbegesetz), keine Gedankenstriche.
# icon: Name aus ICONS in bauen.py

LEISTUNGEN = [
  dict(slug="saubere-zaehne", icon="zahnbuerste", kurz="Prophylaxe & PZR",
       titel="Prophylaxe und professionelle Zahnreinigung",
       teaser="Vorsorge, damit Ihre Zähne ein Leben lang gesund bleiben.",
       intro="Vorsorge ist in der Zahnmedizin die beste Behandlung. Mit regelmäßiger Prophylaxe erkennen wir Veränderungen früh und können bleibenden Schäden vorbeugen. Wir empfehlen Erwachsenen mindestens einen Termin im Jahr, Kindern und Jugendlichen zwischen sechs und 18 Jahren zwei.",
       abschnitte=[
        ("Professionelle Zahnreinigung (PZR)", "Bei der PZR entfernen wir Beläge und Zahnstein, reinigen die Zahnzwischenräume gründlich und polieren die Zähne. Sie ergänzt Ihre tägliche Mundhygiene dort, wo Zahnbürste und Zahnseide nicht hinkommen. Die PZR ist eine Privatleistung. Viele Krankenkassen und Zahnzusatzversicherungen beteiligen sich an den Kosten. Sprechen Sie uns gerne darauf an."),
        ("Richtig putzen, gezielt pflegen", "Im Prophylaxetermin zeigen wir Ihnen, worauf es bei der täglichen Pflege ankommt: die richtige Putztechnik, Zahnseide und Zwischenraumbürsten, die passende Zahnbürste und Zahnpasta. Denn die tägliche Pflege zu Hause bleibt der wichtigste Beitrag für gesunde Zähne."),
        ("Prophylaxe für die Kleinsten", "Auch Kinder profitieren von regelmäßigen Besuchen. So lernen sie unsere Praxis ganz entspannt kennen, und wenn doch einmal eine Behandlung nötig ist, ist die Umgebung schon vertraut."),
       ]),
  dict(slug="schoenes-laecheln", icon="stern", kurz="Ästhetik",
       titel="Ästhetische Zahnheilkunde",
       teaser="Bleaching, Veneers und natürliche Restaurationen für ein schönes Lächeln.",
       intro="Kaffee, Tee, Rauchen oder Medikamente können Zähne mit der Zeit verfärben. Unfälle oder Erkrankungen führen manchmal zu abgebrochenen Zähnen oder Fehlstellungen. Wir bieten Ihnen verschiedene Möglichkeiten, Ihr Lächeln wieder strahlen zu lassen.",
       abschnitte=[
        ("Professionelle Zahnreinigung", "Oft ist eine gründliche professionelle Zahnreinigung schon der erste Schritt zu helleren Zähnen. Beläge und oberflächliche Verfärbungen werden entfernt, die Zähne poliert."),
        ("Bleaching", "Hartnäckige Verfärbungen lassen sich durch ein schonendes Aufhellen der Zähne reduzieren. Wie hell Ihre Zähne werden sollen, besprechen wir vorher ganz individuell mit Ihnen."),
        ("Veneers", "Veneers sind hauchdünne Keramikschalen, die auf die Zahnoberfläche geklebt werden. Sie eignen sich für kleine Defekte, leichte Fehlstellungen oder einzelne verfärbte Zähne."),
        ("Restaurative Behandlung", "Wir bauen abgebrochene Frontzähne wieder auf, schließen kleine Lücken mit zahnfarbenem Komposit und ersetzen fehlende Zähne, zum Beispiel mit Implantaten."),
       ]),
  dict(slug="feste-zaehne", icon="zahnfleisch", kurz="Parodontologie",
       titel="Parodontologie",
       teaser="Früh erkennen und gezielt behandeln, damit Ihre Zähne fest bleiben.",
       intro="Parodontitis ist eine der häufigsten Erkrankungen in der Zahnmedizin und kann in jedem Alter auftreten. Bakterien sammeln sich in den Zahnfleischtaschen zwischen Zahn und Zahnfleisch. Unbehandelt kann das Zahnfleisch zurückgehen, der Knochen abgebaut werden und Zähne können sich lockern.",
       abschnitte=[
        ("Anzeichen ernst nehmen", "Typische Hinweise sind Zahnfleischbluten, Rötungen, Schwellungen oder zurückgehendes Zahnfleisch. Je früher wir eine Parodontitis erkennen, desto besser lässt sie sich behandeln."),
        ("Unsere Spezialistin", "Dr. med. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Parodontologie und ist für Diagnose und Therapie der Parodontitis zuständig."),
        ("Die Behandlung", "Nach einer gründlichen Befundaufnahme erstellen wir Ihren persönlichen Therapieplan. Dazu gehört die schonende Reinigung der Zahnfleischtaschen mit Ultraschall und Handinstrumenten, je nach Befund auch der Einsatz unseres Lasersystems oder der Wiederaufbau von Gewebe und Knochen. Anschließend begleiten wir Sie in der Nachsorge, damit Ihr Zahnfleisch gesund bleibt."),
       ]),
  dict(slug="neue-zaehne", icon="implantat", kurz="Zahnersatz & Implantate",
       titel="Zahnersatz und Implantologie",
       teaser="Füllungen, Kronen, Brücken und Implantate aus dem eigenen Labor.",
       intro="Trotz guter Pflege braucht ein Zahn manchmal eine Füllung oder muss ersetzt werden. Ob Füllung, Inlay, Krone, Brücke oder Implantat: Wir geben Ihnen Ihr gesundes Lächeln zurück, mit hochwertigem Zahnersatz, der lange hält.",
       abschnitte=[
        ("Zahnersatz aus dem eigenen Labor", "Kronen, Brücken und Inlays aus Keramik oder Gold fertigen wir in unserem hauseigenen Dentallabor. Für besondere Fälle und größere Prothesen arbeiten wir mit deutschen Meisterlaboren zusammen."),
        ("Füllungen und Inlays", "Nach dem Entfernen der Karies verschließen wir den Zahn mit einer passenden Füllung aus Kunststoff, Keramik oder Gold. Inlays werden vorab im Labor passgenau gefertigt und dann wie ein Puzzleteil eingesetzt."),
        ("Implantate", "Dr. med. Sabine Messerschmidt hat den Tätigkeitsschwerpunkt Implantologie (DGI und APW). Ein Implantat ist eine künstliche Zahnwurzel, die im Kiefer einheilt und die neue Krone trägt. So lassen sich einzelne Lücken schließen oder größerer Zahnersatz sicher befestigen."),
       ]),
  dict(slug="erhaltende-zaehne", icon="wurzel", kurz="Endodontie",
       titel="Endodontie: Zähne erhalten",
       teaser="Wurzelbehandlung und Wurzelspitzenresektion, damit Ihr eigener Zahn bleibt.",
       intro="Unser Ziel ist es, Ihre eigenen Zähne so lange wie möglich zu erhalten, auch wenn ein Zahn erkrankt ist. Die Endodontie hilft, das Ziehen eines Zahnes zu vermeiden.",
       abschnitte=[
        ("Wurzelkanalbehandlung", "Ist der Zahnnerv entzündet oder abgestorben, entfernen wir das Gewebe im Wurzelkanal vollständig, reinigen und desinfizieren den Kanal und füllen ihn neu. Die Behandlung erfolgt unter örtlicher Betäubung. Häufig ist der Zahn danach wieder voll belastbar."),
        ("Wurzelspitzenresektion", "In besonderen Fällen entfernen wir die entzündete Wurzelspitze in einem kleinen chirurgischen Eingriff über den Kieferknochen."),
        ("Und danach?", "Nach der Behandlung wird der Zahn verschlossen. Ob eine Füllung reicht oder ein Inlay oder eine Krone sinnvoll ist, besprechen wir mit Ihnen anhand des Befundes."),
       ]),
  dict(slug="junge-zaehne", icon="kind", kurz="Kinderzahnheilkunde",
       titel="Kinder- und Jugendzahnheilkunde",
       teaser="Mit Geduld und Humor: der entspannte Zahnarztbesuch für Kinder.",
       intro="Mit dem ersten Zahn kommen viele Fragen: Wie oft putzen? Ab wann selbst putzen? Und wann zum ersten Mal zum Zahnarzt? Unsere Antwort: Kommen Sie gerne, sobald die ersten Zähne da sind.",
       abschnitte=[
        ("Der erste Besuch", "Für Kinder ist der erste Besuch aufregend. Am schönsten ist es, wenn Ihr Kind ohne Beschwerden zum Schnuppern kommt. So lernen wir uns ganz ohne Druck kennen und legen den Grundstein für entspannte Kontrolltermine."),
        ("Vorsorge für Kinderzähne", "Bis sechs Jahre empfehlen wir einen, ab sechs Jahren zwei Kontrolltermine im Jahr. Wir begleiten die Gebissentwicklung beim Zahnwechsel und raten rechtzeitig zu einer kieferorthopädischen Behandlung, wenn sie nötig ist."),
        ("Patenschaft für Kindergärten", "Als Patenschaftszahnarzt im Arbeitskreis Jugendzahnpflege betreuen wir zwei Kindergärten in Mainz-Laubenheim. Die Kinder erkunden einmal im Jahr unsere Praxis, und wir besuchen sie mit Handpuppen und Mitmachspielen im Kindergarten."),
       ]),
  dict(slug="gesundes-kiefergelenk", icon="kiefer", kurz="Funktionsdiagnostik",
       titel="Funktionsdiagnostik und CMD",
       teaser="Wenn Kiefer, Kopf oder Nacken schmerzen: Ursachen gezielt finden.",
       intro="Schmerzen im Kiefergelenk, Verspannungen im Nacken oder Kopfschmerzen können auf eine Craniomandibuläre Dysfunktion (CMD) hinweisen, also eine Störung im Zusammenspiel von Kiefergelenken, Zähnen und Kaumuskulatur.",
       abschnitte=[
        ("So untersuchen wir", "Bei der Funktionsdiagnostik prüfen wir Kiefergelenke und Zähne, die Bewegungen des Unterkiefers und die Kaumuskulatur. Daraus erstellen wir einen Therapieplan, der auf Sie abgestimmt ist."),
        ("Wem wir sie empfehlen", "Eine Funktionsdiagnostik ist sinnvoll bei Beschwerden, die auf eine CMD hindeuten, vor größeren kieferorthopädischen oder konservierenden Behandlungen und vor umfangreichem Zahnersatz."),
       ]),
  dict(slug="stressfreier-besuch", icon="herz", kurz="Angstpatienten",
       titel="Entspannt zum Zahnarzt",
       teaser="Wir nehmen Ihre Sorgen ernst und nehmen uns Zeit für Sie.",
       intro="Sie fühlen sich unwohl beim Gedanken an den nächsten Zahnarzttermin? Dann sind Sie bei uns herzlich willkommen. Wir nehmen Ihre Sorgen ernst und tun alles dafür, dass Sie sich bei uns gut aufgehoben fühlen.",
       abschnitte=[
        ("Sagen Sie es uns", "Sprechen Sie Ihre Angst gerne schon bei der Terminvereinbarung an. Dann planen wir mehr Zeit ein und begleiten Sie vom ersten Kennenlernen bis zum Abschluss der Behandlung."),
        ("Ruhige Atmosphäre", "Unsere hellen, freundlichen Räume und ein Team, das sich Zeit nimmt, sorgen für eine entspannte Stimmung. Wir erklären jeden Schritt, bevor wir ihn machen."),
        ("Begleitende Verfahren", "Neben der örtlichen Betäubung bieten wir auf Wunsch begleitend Akupunktur an. Welche Möglichkeiten für Sie in Frage kommen, besprechen wir gerne persönlich mit Ihnen."),
       ]),
  dict(slug="gekonnte-eingriffe", icon="skalpell", kurz="Oralchirurgie",
       titel="Oralchirurgie",
       teaser="Von der Weisheitszahn-OP bis zum Kieferaufbau, ausführlich erklärt.",
       intro="Die Oralchirurgie umfasst Eingriffe an Zähnen, Mundhöhle und Kiefer. Unser Spektrum reicht von kleinen Eingriffen wie der Korrektur von Lippen- und Zungenbändchen über die Entfernung von Weisheitszähnen bis zu Kiefer- und Zahnfleischoperationen.",
       abschnitte=[
        ("Weisheitszähne", "Weisheitszähne müssen nicht immer entfernt werden. Gründe dafür können Entzündungen oder Platzmangel im Kiefer sein, durch den sich andere Zähne verschieben. Der Eingriff erfolgt meist unter örtlicher Betäubung, auf Wunsch auch in Vollnarkose."),
        ("Wurzelspitzenresektion", "Ist eine Wurzelspitze entzündet, kann sie über einen kleinen chirurgischen Zugang durch den Kieferknochen entfernt werden. So bleibt der Zahn erhalten."),
        ("Ausführliche Aufklärung", "Vor jedem Eingriff nehmen wir uns Zeit für ein Beratungsgespräch und erklären Ihnen alle Schritte. Nach der Operation erhalten Sie von uns klare Hinweise, worauf Sie achten sollten."),
       ]),
]
